CREATE DATABASE IF NOT EXISTS multapps_dev;
USE multapps_dev;

CREATE TABLE IF NOT EXISTS  categoria(
	id INT NOT NULL AUTO_INCREMENT,
    nome VARCHAR(250) NOT NULL,
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    data_alteracao TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    status ENUM ('inativo', 'ativo', 'excluido') NOT NULL,
    
    PRIMARY KEY(id)
);


CREATE TABLE IF NOT EXISTS  produto(
	id INT NOT NULL AUTO_INCREMENT,
	categoria_id INT NOT NULL,
    nome VARCHAR(250) NOT NULL,
    preco DECIMAL NOT NULL,
    quantidade_estoque INT NOT NULL,
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    data_alteracao TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    status ENUM ('inativo', 'ativo', 'excluido') NOT NULL,
    
    PRIMARY KEY(id),
    FOREIGN KEY (categoria_id) REFERENCES categoria(id)
);

CREATE TABLE IF NOT EXISTS  usuario(
	id INT NOT NULL AUTO_INCREMENT,
    nome VARCHAR(250) NOT NULL,
    cpf VARCHAR(14) NOT NULL,
    email VARCHAR(250) NOT NULL,
    senha VARCHAR(50) NOT NULL,
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    data_alteracao TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    data_ultimo_acesso DATETIME,
    status ENUM ('inativo', 'ativo') NOT NULL,
    
    PRIMARY KEY(id)
);